//Posts Actions
export const GET_POSTS_CALL = 'GET_POSTS_CALL';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const RESET_POSTS = 'RESET_POSTS';

//Post Actions
export const GET_POST_COMMENTS_CALL = 'GET_POST_COMMENTS_CALL';
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
export const GET_POST_COMMENTS_ERROR = 'GET_POST_COMMENTS_ERROR';
export const RESET_POST = 'RESET_POST';

//Photos Actions
export const GET_PHOTOS_CALL = 'GET_PHOTOS_CALL';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';
export const RESET_PHOTOS = 'RESET_PHOTOS';

//User Actions
export const GET_USER_INFO_CALL = 'GET_USER_INFO_CALL';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_POSTS_CALL = 'GET_USER_POSTS_CALL';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_TODOS_CALL = 'GET_USER_TODOS_CALL';
export const GET_USER_TODOS_SUCCESS = 'GET_USER_TODOS_SUCCESS';
export const GET_USER_ALBUMS_CALL = 'GET_USER_ALBUMS_CALL';
export const GET_USER_ALBUMS_SUCCESS = 'GET_USER_ALBUMS_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const RESET_USER = 'RESET_USER';
